# Generated by Django 4.1.6 on 2023-02-17 04:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="city",
            field=models.CharField(default="Cali", max_length=180, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="product",
            name="country",
            field=django_countries.fields.CountryField(
                default="CO", max_length=2, verbose_name="Country"
            ),
        ),
    ]
